# Generated by Django 6.0.6 on 2026-06-25 06:57

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.profiles.models.profile_pic_upload_path,
            ),
        ),
    ]
