# Generated by Django 4.2.30 on 2026-06-26 17:21

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='write_up',
            field=models.FileField(blank=True, upload_to=apps.projects.models.project_write_up_upload_path),
        ),
    ]
