/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './templates/**/*.html',
    './apps/**/templates/**/*.html',
    './static/js/**/*.js',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#131b2e',
        'on-primary-container': '#7c839b',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        secondary: '#735c00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed01b',
        'on-secondary-container': '#6f5900',
        'secondary-fixed': '#ffe083',
        'secondary-fixed-dim': '#eec200',
        'on-secondary-fixed': '#231b00',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#191c1e',
        'on-tertiary-container': '#818486',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-tertiary-fixed': '#191c1e',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0d1c2e',
        surface: '#f8f9ff',
        'on-surface': '#0d1c2e',
        'on-surface-variant': '#45464d',
        'surface-variant': '#d5e3fc',
        'surface-dim': '#ccdbf3',
        'surface-bright': '#f8f9ff',
        'surface-container': '#e6eeff',
        'surface-container-low': '#eff4ff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d5e3fc',
        'surface-container-lowest': '#ffffff',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',
        'inverse-surface': '#233144',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#bec6e0',
        'surface-tint': '#565e74',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xxl: '48px',
        xl: '32px',
        lg: '24px',
        md: '16px',
        sm: '12px',
        xs: '4px',
        gutter: '24px',
        'container-padding': '24px',
        'row-height-standard': '48px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-xl': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        'table-data': ['Geist', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
