# Generated by Django 6.0.6 on 2026-06-25 06:57

import apps.courses.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("objectives_json", models.JSONField(blank=True, default=list)),
                (
                    "slides",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.courses.models.slides_upload_path,
                    ),
                ),
                (
                    "notes",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.courses.models.notes_upload_path,
                    ),
                ),
                ("other_resources_json", models.JSONField(blank=True, default=list)),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["week"],
                "unique_together": {("course", "week")},
            },
        ),
    ]
